name = "dev-card"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[triggers]
crons = ["0 */6 * * *"]

[[kv_namespaces]]
binding = "KV"
id = "009c5be350484f448918b4ec8eea8c30"
preview_id = "009c5be350484f448918b4ec8eea8c30"
